Issue 4 refactoring endpoints handler
LevKakalashvili/test_api pull request #9
Opened 2023-02-01 16:25 UTC by LevKakalashvili

2023-02-01 17:12 UTC, saigono requested changes

2023-02-01 17:12 UTC, saigono commented on test_api/main.py
> +    if item_id:
Лучше чтобы `item_id` был обязательным

2023-02-01 17:12 UTC, saigono commented on test_api/main.py
> +    return {"success": True, "data": storage.get_entry(item_id)}
Здесь и ниже в каждом обработчике: давай возвращать 404 если объекта с таким айди не существует.

2023-02-01 17:12 UTC, saigono commented on tests/test_api_endpoints.py
> +entry = Item(id="EN0PhG", software="samba", version="1.2.3")
Не очень хорошо создавать глобальный объект посередине кода

2023-02-02 16:30 UTC, LevKakalashvili commented on test_api/main.py
> +    if item_id:
Вот тут мне не совсем понятно.
id в ендпоинте должен быть, но я предполагаю, что и в теле может быть передан id 
{
    "software": "windows",
    "version": "0.0.3"
}
или
{
   "id: "jhdsjka",
    "software": "windows",
    "version": "0.0.3"
}
но я должен учесть, что при при получении в теле запроса id, этот самый id должен быть такой же как и в эндпоинте,  а иначе, это как мне кажется ошибка и нужно в таком случае возвращать ошибку. Я верно понимаю или что-то не так?
И если я правильно предполагаю, то эту проверку уже надо делать не в самом хэндлере, а уже делать отделать функцию для валидации

2023-02-02 16:39 UTC, saigono commented on test_api/main.py
> +    if item_id:
Да, всё так. Если вдруг передали `id` в теле, и они не совпадают, то возвращать ошибку с кодом 400 и сообщением о том, что айди в теле и в урле не совпадают.

2023-02-02 16:45 UTC, LevKakalashvili commented on test_api/main.py
> +    return {"success": True, "data": storage.get_entry(item_id)}
Если в обработчике генерить 404 ошибку, то как мне кажется мы однозначно должны понимать, что такого объекта нет в бд. В текущей реализации бд, функции get_, update_, delete_, patch_ возвращают False, но это не ответ на вопрос: "есть ли такой объект в бд?". Т.е. нужно ввести в бд новый метод, который будет проверять наличие объекта в бд? Я правильно думаю или слишком много придумываю?

2023-02-02 22:31 UTC, saigono commented on test_api/main.py
> +    return {"success": True, "data": storage.get_entry(item_id)}
Да, нужно однозначно понимать, что объекта нет. У тебя есть метод `get_entry` который ровно это и проверяет, в том числе. Можно его использовать в обработчиках. Или например кидать новое исключение, назовем его `VersionNotFound` и ловить его в обработчиках. Или пойти дальше и ввести новый декоратор который будет сам ловить исключение и возвращать 404. Вариантов множество

2023-02-03 12:43 UTC, saigono requested changes

2023-02-03 12:43 UTC, saigono commented on test_api/main.py
> +        item.check_id(item_id)
не очень понятно зачем это выносить в функцию дополнительную, а не проверять тут.

2023-02-03 12:43 UTC, saigono commented on test_api/models.py
> +            if self.id != value:
```suggestion
        if self.id is not None and self.id != value:
```

2023-02-03 12:43 UTC, saigono commented on tests/test_api_endpoints.py
> +        ("/versions", 200, {"success": True, "data": data_out_default}),
Для `/versions` не хватает теста "Если версий ещё нет, то всё равно возвращаем 200 и пустой список"

2023-02-03 12:43 UTC, saigono commented on tests/test_api_endpoints.py
> +    response = client.get(uri)
Почему этот тест делает `get`-запрос? Ничего кроме `post` не нужно.

2023-02-03 12:43 UTC, saigono commented on tests/test_api_endpoints.py
> +        assert len(response.json()["data"]) == len_ + 1
Это вообще какая-то магия здесь происходит (я понимаю зачем, но не надо так)

2023-02-03 12:43 UTC, saigono commented on test_api/db.py
> +            entry.id is not None
Я пропустил этот момент. id должна генерировать сама система, а не пользователь.

2023-02-03 12:43 UTC, saigono commented on tests/test_api_endpoints.py
> +    response = client.get(uri)
Опять же, тут `get` не нужен, работай непосредственно с базой

2023-02-04 11:40 UTC, LevKakalashvili commented on test_api/main.py
> +        item.check_id(item_id)
Считал что в хендлере, это делать не хорошо

2023-02-04 11:46 UTC, LevKakalashvili commented on tests/test_api_endpoints.py
> +        ("/versions", 200, {"success": True, "data": data_out_default}),
В текущей реализации, не может быть ситуации, чтобы база была пуста. Предлагаю, этот тест написать когда будет SQL
Я сделал TODO в тесте, чтоб не забыть его включить

2023-02-04 22:06 UTC, saigono approved these changes
Есть ещё помарки, но в целом можно мержить

2023-02-04 22:06 UTC, saigono commented on tests/test_api_endpoints.py
> +        ("/versions", 200, {"success": True, "data": data_out_default}),
Хитро

2023-02-04 22:06 UTC, saigono commented on tests/test_api_endpoints.py
> +    len_ = len(storage.data.items())
Не говорящее имя, лучше что-то вроде `old_storage_len`

2023-02-05 12:58 UTC, merged